// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "github.com/vulcangz/gf2-authz/internal/logic/manager"
	_ "github.com/vulcangz/gf2-authz/internal/logic/middleware"
	_ "github.com/vulcangz/gf2-authz/internal/logic/sys"
)
