version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.67.0
    ports:
      - 4317:4317
      - 4318:4318
      - 14250:14250
      - 14268:14268
      - 14269:14269
      - 16686:16686
      - 9411:9411
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    volumes:
      - jaeger-data:/jaeger

volumes:
  jaeger-data:
