// ==========================================================================
// Code generated and maintained by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.4
// 	protoc        v5.29.3
// source: pbentity/audits.proto

package pbentity

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Audits struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`                      //
	Date          *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=Date,proto3" json:"Date,omitempty"`                   //
	Principal     string                 `protobuf:"bytes,3,opt,name=Principal,proto3" json:"Principal,omitempty"`         //
	ResourceKind  string                 `protobuf:"bytes,4,opt,name=ResourceKind,proto3" json:"ResourceKind,omitempty"`   //
	ResourceValue string                 `protobuf:"bytes,5,opt,name=ResourceValue,proto3" json:"ResourceValue,omitempty"` //
	Action        string                 `protobuf:"bytes,6,opt,name=Action,proto3" json:"Action,omitempty"`               //
	IsAllowed     int64                  `protobuf:"varint,7,opt,name=IsAllowed,proto3" json:"IsAllowed,omitempty"`        //
	PolicyId      string                 `protobuf:"bytes,8,opt,name=PolicyId,proto3" json:"PolicyId,omitempty"`           //
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Audits) Reset() {
	*x = Audits{}
	mi := &file_pbentity_audits_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Audits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Audits) ProtoMessage() {}

func (x *Audits) ProtoReflect() protoreflect.Message {
	mi := &file_pbentity_audits_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Audits.ProtoReflect.Descriptor instead.
func (*Audits) Descriptor() ([]byte, []int) {
	return file_pbentity_audits_proto_rawDescGZIP(), []int{0}
}

func (x *Audits) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Audits) GetDate() *timestamppb.Timestamp {
	if x != nil {
		return x.Date
	}
	return nil
}

func (x *Audits) GetPrincipal() string {
	if x != nil {
		return x.Principal
	}
	return ""
}

func (x *Audits) GetResourceKind() string {
	if x != nil {
		return x.ResourceKind
	}
	return ""
}

func (x *Audits) GetResourceValue() string {
	if x != nil {
		return x.ResourceValue
	}
	return ""
}

func (x *Audits) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Audits) GetIsAllowed() int64 {
	if x != nil {
		return x.IsAllowed
	}
	return 0
}

func (x *Audits) GetPolicyId() string {
	if x != nil {
		return x.PolicyId
	}
	return ""
}

var File_pbentity_audits_proto protoreflect.FileDescriptor

var file_pbentity_audits_proto_rawDesc = string([]byte{
	0x0a, 0x15, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2f, 0x61, 0x75, 0x64, 0x69, 0x74,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x62, 0x65, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x82, 0x02, 0x0a, 0x06, 0x41, 0x75, 0x64, 0x69, 0x74, 0x73, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x2e, 0x0a,
	0x04, 0x44, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f,
	0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69,
	0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x44, 0x61, 0x74, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x50, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x50, 0x72, 0x69, 0x6e, 0x63, 0x69, 0x70, 0x61, 0x6c, 0x12, 0x22, 0x0a, 0x0c, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x12,
	0x24, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a,
	0x09, 0x49, 0x73, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x49, 0x73, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x65, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x50,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x50,
	0x6f, 0x6c, 0x69, 0x63, 0x79, 0x49, 0x64, 0x42, 0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x75, 0x6c, 0x63, 0x61, 0x6e, 0x67, 0x7a, 0x2f, 0x67,
	0x66, 0x32, 0x2d, 0x61, 0x75, 0x74, 0x68, 0x7a, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x62, 0x65,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_pbentity_audits_proto_rawDescOnce sync.Once
	file_pbentity_audits_proto_rawDescData []byte
)

func file_pbentity_audits_proto_rawDescGZIP() []byte {
	file_pbentity_audits_proto_rawDescOnce.Do(func() {
		file_pbentity_audits_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pbentity_audits_proto_rawDesc), len(file_pbentity_audits_proto_rawDesc)))
	})
	return file_pbentity_audits_proto_rawDescData
}

var file_pbentity_audits_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pbentity_audits_proto_goTypes = []any{
	(*Audits)(nil),                // 0: pbentity.Audits
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_pbentity_audits_proto_depIdxs = []int32{
	1, // 0: pbentity.Audits.Date:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pbentity_audits_proto_init() }
func file_pbentity_audits_proto_init() {
	if File_pbentity_audits_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pbentity_audits_proto_rawDesc), len(file_pbentity_audits_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pbentity_audits_proto_goTypes,
		DependencyIndexes: file_pbentity_audits_proto_depIdxs,
		MessageInfos:      file_pbentity_audits_proto_msgTypes,
	}.Build()
	File_pbentity_audits_proto = out.File
	file_pbentity_audits_proto_goTypes = nil
	file_pbentity_audits_proto_depIdxs = nil
}
