// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/vulcangz/gf2-authz/internal/dao/internal"
)

// internalAuthzAuditDao is internal type for wrapping internal DAO implements.
type internalAuthzAuditDao = *internal.AuthzAuditDao

// authzAuditDao is the data access object for table authz_audit.
// You can define custom methods on it to extend its functionality as you wish.
type authzAuditDao struct {
	internalAuthzAuditDao
}

var (
	// Audit is globally public accessible object for table authz_audit operations.
	Audit = authzAuditDao{
		internal.NewAuthzAuditDao(),
	}
)

// Fill with you ideas below.
