// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/vulcangz/gf2-authz/internal/dao/internal"
)

// internalAuthzResourcesDao is internal type for wrapping internal DAO implements.
type internalAuthzResourcesDao = *internal.AuthzResourcesDao

// authzResourcesDao is the data access object for table authz_resources.
// You can define custom methods on it to extend its functionality as you wish.
type authzResourcesDao struct {
	internalAuthzResourcesDao
}

var (
	// Resource is globally public accessible object for table authz_resources operations.
	Resource = authzResourcesDao{
		internal.NewAuthzResourcesDao(),
	}
)

// Fill with you ideas below.
