// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/vulcangz/gf2-authz/internal/dao/internal"
)

// internalAuthzPoliciesResourcesDao is internal type for wrapping internal DAO implements.
type internalAuthzPoliciesResourcesDao = *internal.AuthzPoliciesResourcesDao

// authzPoliciesResourcesDao is the data access object for table authz_policies_resources.
// You can define custom methods on it to extend its functionality as you wish.
type authzPoliciesResourcesDao struct {
	internalAuthzPoliciesResourcesDao
}

var (
	// AuthzPoliciesResources is globally public accessible object for table authz_policies_resources operations.
	AuthzPoliciesResources = authzPoliciesResourcesDao{
		internal.NewAuthzPoliciesResourcesDao(),
	}
)

// Fill with you ideas below.
