// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/vulcangz/gf2-authz/internal/dao/internal"
)

// internalAuthzPrincipalsDao is internal type for wrapping internal DAO implements.
type internalAuthzPrincipalsDao = *internal.AuthzPrincipalsDao

// authzPrincipalsDao is the data access object for table authz_principals.
// You can define custom methods on it to extend its functionality as you wish.
type authzPrincipalsDao struct {
	internalAuthzPrincipalsDao
}

var (
	// Principal is globally public accessible object for table authz_principals operations.
	Principal = authzPrincipalsDao{
		internal.NewAuthzPrincipalsDao(),
	}
)

// Fill with you ideas below.
