// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/vulcangz/gf2-authz/internal/dao/internal"
)

// internalAuthzOauthTokensDao is internal type for wrapping internal DAO implements.
type internalAuthzOauthTokensDao = *internal.AuthzOauthTokensDao

// authzOauthTokensDao is the data access object for table authz_oauth_tokens.
// You can define custom methods on it to extend its functionality as you wish.
type authzOauthTokensDao struct {
	internalAuthzOauthTokensDao
}

var (
	// Token is globally public accessible object for table authz_oauth_tokens operations.
	Token = authzOauthTokensDao{
		internal.NewAuthzOauthTokensDao(),
	}
)

// Fill with you ideas below.
