// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/vulcangz/gf2-authz/internal/dao/internal"
)

// internalAuthzPrincipalsAttributesDao is internal type for wrapping internal DAO implements.
type internalAuthzPrincipalsAttributesDao = *internal.AuthzPrincipalsAttributesDao

// authzPrincipalsAttributesDao is the data access object for table authz_principals_attributes.
// You can define custom methods on it to extend its functionality as you wish.
type authzPrincipalsAttributesDao struct {
	internalAuthzPrincipalsAttributesDao
}

var (
	// AuthzPrincipalsAttributes is globally public accessible object for table authz_principals_attributes operations.
	AuthzPrincipalsAttributes = authzPrincipalsAttributesDao{
		internal.NewAuthzPrincipalsAttributesDao(),
	}
)

// Fill with you ideas below.
