// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/vulcangz/gf2-authz/internal/dao/internal"
)

// internalAuthzStatsDao is internal type for wrapping internal DAO implements.
type internalAuthzStatsDao = *internal.AuthzStatsDao

// authzStatsDao is the data access object for table authz_stats.
// You can define custom methods on it to extend its functionality as you wish.
type authzStatsDao struct {
	internalAuthzStatsDao
}

var (
	// Stats is globally public accessible object for table authz_stats operations.
	Stats = authzStatsDao{
		internal.NewAuthzStatsDao(),
	}
)

// Fill with you ideas below.
