// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/vulcangz/gf2-authz/internal/dao/internal"
)

// internalAuthzCompiledPoliciesDao is internal type for wrapping internal DAO implements.
type internalAuthzCompiledPoliciesDao = *internal.AuthzCompiledPoliciesDao

// authzCompiledPoliciesDao is the data access object for table authz_compiled_policies.
// You can define custom methods on it to extend its functionality as you wish.
type authzCompiledPoliciesDao struct {
	internalAuthzCompiledPoliciesDao
}

var (
	// CompiledPolicy is globally public accessible object for table authz_compiled_policies operations.
	CompiledPolicy = authzCompiledPoliciesDao{
		internal.NewAuthzCompiledPoliciesDao(),
	}
)

// Fill with you ideas below.
