// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/vulcangz/gf2-authz/internal/dao/internal"
)

// internalAuthzPoliciesActionsDao is internal type for wrapping internal DAO implements.
type internalAuthzPoliciesActionsDao = *internal.AuthzPoliciesActionsDao

// authzPoliciesActionsDao is the data access object for table authz_policies_actions.
// You can define custom methods on it to extend its functionality as you wish.
type authzPoliciesActionsDao struct {
	internalAuthzPoliciesActionsDao
}

var (
	// AuthzPoliciesActions is globally public accessible object for table authz_policies_actions operations.
	AuthzPoliciesActions = authzPoliciesActionsDao{
		internal.NewAuthzPoliciesActionsDao(),
	}
)

// Fill with you ideas below.
