// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/vulcangz/gf2-authz/internal/dao/internal"
)

// internalAuthzClientsDao is internal type for wrapping internal DAO implements.
type internalAuthzClientsDao = *internal.AuthzClientsDao

// authzClientsDao is the data access object for table authz_clients.
// You can define custom methods on it to extend its functionality as you wish.
type authzClientsDao struct {
	internalAuthzClientsDao
}

var (
	// Client is globally public accessible object for table authz_clients operations.
	Client = authzClientsDao{
		internal.NewAuthzClientsDao(),
	}
)

// Fill with you ideas below.
