// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/vulcangz/gf2-authz/internal/dao/internal"
)

// internalAuthzResourcesAttributesDao is internal type for wrapping internal DAO implements.
type internalAuthzResourcesAttributesDao = *internal.AuthzResourcesAttributesDao

// authzResourcesAttributesDao is the data access object for table authz_resources_attributes.
// You can define custom methods on it to extend its functionality as you wish.
type authzResourcesAttributesDao struct {
	internalAuthzResourcesAttributesDao
}

var (
	// AuthzResourcesAttributes is globally public accessible object for table authz_resources_attributes operations.
	AuthzResourcesAttributes = authzResourcesAttributesDao{
		internal.NewAuthzResourcesAttributesDao(),
	}
)

// Fill with you ideas below.
