// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/vulcangz/gf2-authz/internal/dao/internal"
)

// internalAuthzPrincipalsRolesDao is internal type for wrapping internal DAO implements.
type internalAuthzPrincipalsRolesDao = *internal.AuthzPrincipalsRolesDao

// authzPrincipalsRolesDao is the data access object for table authz_principals_roles.
// You can define custom methods on it to extend its functionality as you wish.
type authzPrincipalsRolesDao struct {
	internalAuthzPrincipalsRolesDao
}

var (
	// AuthzPrincipalsRoles is globally public accessible object for table authz_principals_roles operations.
	AuthzPrincipalsRoles = authzPrincipalsRolesDao{
		internal.NewAuthzPrincipalsRolesDao(),
	}
)

// Fill with you ideas below.
